sudo: false
language: julia
os:
#    - osx  # Skip OS X until intermitent failures can be resolved.
    - linux
julia:
    - 0.3
    - 0.4
    - nightly

notifications:
    email: false

addons:
  apt:
    packages:
    - gfortran

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Dierckx"); Pkg.test("Dierckx"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Dierckx")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
